// SAMODEJNO ZAJETO: AI ocena gnece na mejnih prehodih (Claude Haiku 4.5 vision).
// Viri: AMS-RS + BIHAMK (BiH stran) in HAK (HR stran). Steje le kolono proti rampi (ne parkiranih).
// 'enter' = koda drzave, v katero kolona vstopa. OPOMBA: priblizek iz slike, ni uradni podatek.
export interface AiCongestion { crId: string; crossing: string; side: string; lat: number; lng: number; image: string; enter: string; dirLabel: string; level: string; extent: string; lanes: number | null; note: string; readable: boolean; ts: string }
export const AI_CONGESTION: AiCongestion[] = [
 {
  "crId": "ba-bijaca",
  "crossing": "GP Bijača",
  "side": "BA",
  "lat": 43.17,
  "lng": 17.49,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/BIJACA.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Krajša kolona vozil pri mejni rampi.",
  "readable": true,
  "ts": "2026-06-23T21:18:04.388Z"
 },
 {
  "crId": "ba-bijaca",
  "crossing": "Nova Sela / Bijaca · kam 1",
  "side": "HAK",
  "lat": 43.17,
  "lng": 17.49,
  "image": "https://m.hak.hr/cam.asp?id=201",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dvopasna, vstop v Hrvaško",
  "readable": true,
  "ts": "2026-06-23T21:18:04.808Z"
 },
 {
  "crId": "ba-bijaca",
  "crossing": "Nova Sela / Bijaca · kam 2",
  "side": "HAK",
  "lat": 43.17,
  "lng": 17.49,
  "image": "https://m.hak.hr/cam.asp?id=202",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Krajša kolona pri rampi, dve vzporedni pasovi",
  "readable": true,
  "ts": "2026-06-23T21:18:05.214Z"
 },
 {
  "crId": "ba-brcko",
  "crossing": "Gunja · kam 1",
  "side": "HAK",
  "lat": 44.88,
  "lng": 18.84,
  "image": "https://m.hak.hr/cam.asp?id=431",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta praktično prazna, le eno vozilo pri rampi",
  "readable": true,
  "ts": "2026-06-23T21:18:13.477Z"
 },
 {
  "crId": "ba-brcko",
  "crossing": "Gunja · kam 2",
  "side": "HAK",
  "lat": 44.88,
  "lng": 18.84,
  "image": "https://m.hak.hr/cam.asp?id=432",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:14.137Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "GP Brod · vstop v BiH",
  "side": "BA",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://gp.satwork.net/AMSRS_04_GP_BR02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona dveh pasov pred rampo.",
  "readable": true,
  "ts": "2026-06-23T21:17:39.147Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "GP Brod · izstop iz BiH",
  "side": "BA",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://gp.satwork.net/AMSRS_04_GP_BR01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri mejni rampi, dva pasova",
  "readable": true,
  "ts": "2026-06-23T21:17:39.365Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "Slavonski Brod · kam 1",
  "side": "HAK",
  "lat": 45.16,
  "lng": 18.01,
  "image": "https://m.hak.hr/cam.asp?id=195",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:41.410Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "Slavonski Brod · kam 2",
  "side": "HAK",
  "lat": 45.16,
  "lng": 18.01,
  "image": "https://m.hak.hr/cam.asp?id=196",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Prosta cesta, nobenih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:41.479Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "Bosanski Brod (BIH) · kam 1",
  "side": "HAK",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://m.hak.hr/cam.asp?id=402",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "gneca",
  "extent": "srednja",
  "lanes": 2,
  "note": "Kolona vozil čaka na vstop v BiH",
  "readable": true,
  "ts": "2026-06-23T21:17:41.545Z"
 },
 {
  "crId": "ba-brod",
  "crossing": "Bosanski Brod (BIH) · kam 2",
  "side": "HAK",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://m.hak.hr/cam.asp?id=403",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona tovornjakov pred mejno rampo",
  "readable": true,
  "ts": "2026-06-23T21:17:43.446Z"
 },
 {
  "crId": "ba-crveni-grm",
  "crossing": "GP Crveni Grm",
  "side": "BA",
  "lat": 43.2,
  "lng": 17.65,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/CRVENIGRM.jpg",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:03.008Z"
 },
 {
  "crId": "ba-crveni-grm",
  "crossing": "Crveni Grm (BIH)",
  "side": "HAK",
  "lat": 43.2,
  "lng": 17.65,
  "image": "https://m.hak.hr/cam.asp?id=410",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:03.407Z"
 },
 {
  "crId": "ba-doljani",
  "crossing": "GP Doljani - ulaz u BIH",
  "side": "BA",
  "lat": 43.02,
  "lng": 17.55,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/DOLJANI.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Nekaj vozil pri kontrolni rampi, mirna situacija.",
  "readable": true,
  "ts": "2026-06-23T21:18:03.879Z"
 },
 {
  "crId": "ba-gabela-polje",
  "crossing": "Metkovic · kam 1",
  "side": "HAK",
  "lat": 43.05,
  "lng": 17.65,
  "image": "https://m.hak.hr/cam.asp?id=321",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Rampa prosta, le eno vozilo pri kontroli.",
  "readable": true,
  "ts": "2026-06-23T21:18:15.601Z"
 },
 {
  "crId": "ba-gabela-polje",
  "crossing": "Metkovic · kam 2",
  "side": "HAK",
  "lat": 43.05,
  "lng": 17.65,
  "image": "https://m.hak.hr/cam.asp?id=320",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil pri rampi.",
  "readable": true,
  "ts": "2026-06-23T21:18:16.267Z"
 },
 {
  "crId": "ba-gradina",
  "crossing": "GP Gradina (Donja Gradina) · izstop iz BiH",
  "side": "BA",
  "lat": 45.27,
  "lng": 16.93,
  "image": "https://gp.satwork.net/AMSRS_08_GP_GD01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dve vzporedni vrsti.",
  "readable": true,
  "ts": "2026-06-23T21:17:35.553Z"
 },
 {
  "crId": "ba-gradina",
  "crossing": "GP Gradina (Donja Gradina) · vstop v BiH",
  "side": "BA",
  "lat": 45.27,
  "lng": 16.93,
  "image": "https://gp.satwork.net/AMSRS_08_GP_GD02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dve vozili v vrsti",
  "readable": true,
  "ts": "2026-06-23T21:17:35.718Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Stara Gradiska · kam 1",
  "side": "HAK",
  "lat": 45.15,
  "lng": 17.25,
  "image": "https://m.hak.hr/cam.asp?id=60",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, le servisna vozila.",
  "readable": true,
  "ts": "2026-06-23T21:17:29.102Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "GP Gradiška · vstop v BiH",
  "side": "BA",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://gp.satwork.net/AMSRS_17_GP_CA02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez čakajočih vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:29.451Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "GP Gradiška · izstop iz BiH",
  "side": "BA",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://gp.satwork.net/AMSRS_17_GP_CA01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, ni vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:29.956Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Stara Gradiska · kam 2",
  "side": "HAK",
  "lat": 45.15,
  "lng": 17.25,
  "image": "https://m.hak.hr/cam.asp?id=59",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:30.817Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Bosanska Gradiska (BIH) · kam 1",
  "side": "HAK",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://m.hak.hr/cam.asp?id=404",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Krajša kolona vozil pred rampo, nizka aktivnost.",
  "readable": true,
  "ts": "2026-06-23T21:17:30.872Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Gornji Varos · kam 2",
  "side": "HAK",
  "lat": 45.15,
  "lng": 17.26,
  "image": "https://m.hak.hr/cam.asp?id=1022",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Večinoma prosta cesta, le eno vozilo pri rampi",
  "readable": true,
  "ts": "2026-06-23T21:17:32.458Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Gornji Varos · kam 1",
  "side": "HAK",
  "lat": 45.15,
  "lng": 17.26,
  "image": "https://m.hak.hr/cam.asp?id=1021",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zastoj",
  "extent": "dolga",
  "lanes": 2,
  "note": "Dolga kolona vozil čaka na kontrolo v Hrvaško",
  "readable": true,
  "ts": "2026-06-23T21:17:32.460Z"
 },
 {
  "crId": "ba-gradiska",
  "crossing": "Bosanska Gradiska (BIH) · kam 2",
  "side": "HAK",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://m.hak.hr/cam.asp?id=405",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona vozil pri mejni rampi",
  "readable": true,
  "ts": "2026-06-23T21:17:33.271Z"
 },
 {
  "crId": "ba-hum",
  "crossing": "GP Hum · izstop iz BiH",
  "side": "BA",
  "lat": 43.34,
  "lng": 18.84,
  "image": "https://gp.satwork.net/AMSRS_13_GP_SP01/slika.jpg",
  "enter": "ME",
  "dirLabel": "vstop v Črno goro",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, nobene vidne kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:51.729Z"
 },
 {
  "crId": "ba-ivanica",
  "crossing": "Ivanica (BIH)",
  "side": "HAK",
  "lat": 42.62,
  "lng": 18.2,
  "image": "https://m.hak.hr/cam.asp?id=414",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, ni stoječih vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:17.778Z"
 },
 {
  "crId": "ba-ivanica",
  "crossing": "Brgat · kam 1",
  "side": "HAK",
  "lat": 42.63,
  "lng": 18.18,
  "image": "https://m.hak.hr/cam.asp?id=453",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri mejni rampi, dva pasova",
  "readable": true,
  "ts": "2026-06-23T21:18:17.986Z"
 },
 {
  "crId": "ba-ivanica",
  "crossing": "Brgat · kam 2",
  "side": "HAK",
  "lat": 42.63,
  "lng": 18.18,
  "image": "https://m.hak.hr/cam.asp?id=454",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta je popolnoma prosta, nobene kolone.",
  "readable": true,
  "ts": "2026-06-23T21:18:18.068Z"
 },
 {
  "crId": "ba-izacic",
  "crossing": "GP Izačić",
  "side": "BA",
  "lat": 44.85,
  "lng": 15.78,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/IZACIC.jpg",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:05.868Z"
 },
 {
  "crId": "ba-izacic",
  "crossing": "Izacic (BIH)",
  "side": "HAK",
  "lat": 44.85,
  "lng": 15.78,
  "image": "https://m.hak.hr/cam.asp?id=407",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona vozil pri kontrolnih kabinah",
  "readable": true,
  "ts": "2026-06-23T21:18:06.579Z"
 },
 {
  "crId": "ba-kamensko",
  "crossing": "GP Kamensko",
  "side": "BA",
  "lat": 43.65,
  "lng": 16.86,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/KAMENSKO.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Eno vozilo v koloni pred rampo.",
  "readable": true,
  "ts": "2026-06-23T21:18:01.230Z"
 },
 {
  "crId": "ba-kamensko",
  "crossing": "Kamensko · kam 1",
  "side": "HAK",
  "lat": 43.65,
  "lng": 16.86,
  "image": "https://m.hak.hr/cam.asp?id=317",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Rampa popolnoma prazna, brez čakajočih vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:02.164Z"
 },
 {
  "crId": "ba-kamensko",
  "crossing": "Kamensko · kam 2",
  "side": "HAK",
  "lat": 43.65,
  "lng": 16.86,
  "image": "https://m.hak.hr/cam.asp?id=318",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Krajša kolona pri rampi, dve vzporedni liniji",
  "readable": true,
  "ts": "2026-06-23T21:18:02.205Z"
 },
 {
  "crId": "ba-karakaj",
  "crossing": "GP Karakaj · vstop v BiH",
  "side": "BA",
  "lat": 44.4,
  "lng": 19.13,
  "image": "https://gp.satwork.net/AMSRS_07_GP_KA02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Slika premno; ni jasne vidljivosti vozil",
  "readable": false,
  "ts": "2026-06-23T21:17:45.034Z"
 },
 {
  "crId": "ba-karakaj",
  "crossing": "GP Karakaj · izstop iz BiH",
  "side": "BA",
  "lat": 44.4,
  "lng": 19.13,
  "image": "https://gp.satwork.net/AMSRS_07_GP_KA01/slika.jpg",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Nočna snemanja, cesta praktično prazna",
  "readable": false,
  "ts": "2026-06-23T21:17:45.175Z"
 },
 {
  "crId": "ba-klobuk",
  "crossing": "GP Klobuk · vstop v BiH",
  "side": "BA",
  "lat": 42.92,
  "lng": 18.45,
  "image": "https://gp.satwork.net/AMSRS_12_GP_KL02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prazna, nobenih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:50.925Z"
 },
 {
  "crId": "ba-klobuk",
  "crossing": "GP Klobuk · izstop iz BiH",
  "side": "BA",
  "lat": 42.92,
  "lng": 18.45,
  "image": "https://gp.satwork.net/AMSRS_12_GP_KL01/slika.jpg",
  "enter": "ME",
  "dirLabel": "vstop v Črno goro",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, ni vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:54.694Z"
 },
 {
  "crId": "ba-kostajnica",
  "crossing": "GP Kostajnica · vstop v BiH",
  "side": "BA",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://gp.satwork.net/AMSRS_11_GP_KO02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, nobena kolona",
  "readable": true,
  "ts": "2026-06-23T21:17:48.681Z"
 },
 {
  "crId": "ba-kostajnica",
  "crossing": "GP Kostajnica · izstop iz BiH",
  "side": "BA",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://gp.satwork.net/AMSRS_11_GP_KO01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Majhna kolona pred kontrolo, večinoma prosto",
  "readable": true,
  "ts": "2026-06-23T21:17:49.210Z"
 },
 {
  "crId": "ba-kostajnica",
  "crossing": "Hrvatska Kostajnica · kam 1",
  "side": "HAK",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://m.hak.hr/cam.asp?id=1019",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, ni vidne kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:49.857Z"
 },
 {
  "crId": "ba-kostajnica",
  "crossing": "Hrvatska Kostajnica · kam 2",
  "side": "HAK",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://m.hak.hr/cam.asp?id=1020",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta proti rampi popolnoma prosta, brez vozil.",
  "readable": true,
  "ts": "2026-06-23T21:17:50.337Z"
 },
 {
  "crId": "ba-kozarska-dubica",
  "crossing": "GP Kozarska Dubica · vstop v BiH",
  "side": "BA",
  "lat": 45.18,
  "lng": 16.81,
  "image": "https://gp.satwork.net/AMSRS_09_GP_KD02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta je prazna, brez vidnih vozil v koloni.",
  "readable": true,
  "ts": "2026-06-23T21:17:46.022Z"
 },
 {
  "crId": "ba-kozarska-dubica",
  "crossing": "GP Kozarska Dubica · izstop iz BiH",
  "side": "BA",
  "lat": 45.18,
  "lng": 16.81,
  "image": "https://gp.satwork.net/AMSRS_09_GP_KD01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Majhna kolona vozil pred mejno rampo",
  "readable": true,
  "ts": "2026-06-23T21:17:47.608Z"
 },
 {
  "crId": "ba-neum-ii",
  "crossing": "Klek / Neum 1 · kam 1",
  "side": "HAK",
  "lat": 42.92,
  "lng": 17.57,
  "image": "https://m.hak.hr/cam.asp?id=203",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prazna, ni vidne kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:16.286Z"
 },
 {
  "crId": "ba-novi-grad",
  "crossing": "GP Novi Grad · vstop v BiH",
  "side": "BA",
  "lat": 45.05,
  "lng": 16.38,
  "image": "https://gp.satwork.net/AMSRS_10_GP_NG02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Povsem prazna cesta, ni vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:17:46.904Z"
 },
 {
  "crId": "ba-novi-grad",
  "crossing": "GP Novi Grad · izstop iz BiH",
  "side": "BA",
  "lat": 45.05,
  "lng": 16.38,
  "image": "https://gp.satwork.net/AMSRS_10_GP_NG01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, nobene kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:48.455Z"
 },
 {
  "crId": "ba-orasje",
  "crossing": "GP Orašje - izlaz iz BIH",
  "side": "BA",
  "lat": 45.03,
  "lng": 18.69,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/ORASJE.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Vozila čakajo na kontrolo ob rampi",
  "readable": true,
  "ts": "2026-06-23T21:17:59.209Z"
 },
 {
  "crId": "ba-orasje",
  "crossing": "Zupanja · kam 1",
  "side": "HAK",
  "lat": 45.01,
  "lng": 18.7,
  "image": "https://m.hak.hr/cam.asp?id=79",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Majhna kolona vozil pri mejni rampi proti HR",
  "readable": true,
  "ts": "2026-06-23T21:17:59.758Z"
 },
 {
  "crId": "ba-orasje",
  "crossing": "Zupanja · kam 2",
  "side": "HAK",
  "lat": 45.01,
  "lng": 18.7,
  "image": "https://m.hak.hr/cam.asp?id=80",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dva pasova vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:00.493Z"
 },
 {
  "crId": "ba-orasje",
  "crossing": "Orasje (BIH)",
  "side": "HAK",
  "lat": 45.03,
  "lng": 18.69,
  "image": "https://m.hak.hr/cam.asp?id=401",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Manjša kolona vozil pred mejno rampo",
  "readable": true,
  "ts": "2026-06-23T21:18:00.584Z"
 },
 {
  "crId": "ba-raca",
  "crossing": "GP Rača · izstop iz BiH",
  "side": "BA",
  "lat": 44.9,
  "lng": 19.32,
  "image": "https://gp.satwork.net/AMSRS_02_GP_RA01/slika.jpg",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Dve vozili v koloni, čakanje pri rampi.",
  "readable": true,
  "ts": "2026-06-23T21:17:37.580Z"
 },
 {
  "crId": "ba-raca",
  "crossing": "GP Rača · vstop v BiH",
  "side": "BA",
  "lat": 44.9,
  "lng": 19.32,
  "image": "https://gp.satwork.net/AMSRS_02_GP_RA02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, nobene kolone vidne",
  "readable": true,
  "ts": "2026-06-23T21:17:39.298Z"
 },
 {
  "crId": "ba-samac",
  "crossing": "GP Šamac · vstop v BiH",
  "side": "BA",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://gp.satwork.net/AMSRS_15_GP_SA02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zastoj",
  "extent": "dolga",
  "lanes": 2,
  "note": "Gosta meglica, kolona sega čez vidno cesto.",
  "readable": false,
  "ts": "2026-06-23T21:17:55.861Z"
 },
 {
  "crId": "ba-samac",
  "crossing": "Slavonski Samac · kam 1",
  "side": "HAK",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://m.hak.hr/cam.asp?id=1015",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dva vzporedna pasova",
  "readable": true,
  "ts": "2026-06-23T21:17:56.007Z"
 },
 {
  "crId": "ba-samac",
  "crossing": "GP Šamac · izstop iz BiH",
  "side": "BA",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://gp.satwork.net/AMSRS_15_GP_SA01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta proti rampi popolnoma prazna, brez kolone.",
  "readable": true,
  "ts": "2026-06-23T21:17:57.038Z"
 },
 {
  "crId": "ba-samac",
  "crossing": "Slavonski Samac · kam 2",
  "side": "HAK",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://m.hak.hr/cam.asp?id=1016",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:57.326Z"
 },
 {
  "crId": "ba-sepak",
  "crossing": "GP Šepak · vstop v BiH",
  "side": "BA",
  "lat": 44.55,
  "lng": 19.18,
  "image": "https://gp.satwork.net/AMSRS_06_GP_SP02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Dve vozili v koloni pri rampi, dostop v Srbijo",
  "readable": true,
  "ts": "2026-06-23T21:17:43.599Z"
 },
 {
  "crId": "ba-sepak",
  "crossing": "GP Šepak · izstop iz BiH",
  "side": "BA",
  "lat": 44.55,
  "lng": 19.18,
  "image": "https://gp.satwork.net/AMSRS_06_GP_SP01/slika.jpg",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Eno vozilo v koloni pred rampo.",
  "readable": true,
  "ts": "2026-06-23T21:17:43.694Z"
 },
 {
  "crId": "ba-svilaj",
  "crossing": "GP Svilaj · vstop v BiH",
  "side": "BA",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://gp.satwork.net/AMSRS_14_GP_SV02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Dva vozila v koloni pred rampo",
  "readable": true,
  "ts": "2026-06-23T21:17:52.258Z"
 },
 {
  "crId": "ba-svilaj",
  "crossing": "GP Svilaj · izstop iz BiH",
  "side": "BA",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://gp.satwork.net/AMSRS_14_GP_SV01/slika.jpg",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Dve vozili v koloni pred rampo.",
  "readable": true,
  "ts": "2026-06-23T21:17:53.064Z"
 },
 {
  "crId": "ba-svilaj",
  "crossing": "Svilaj · kam 1",
  "side": "HAK",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://m.hak.hr/cam.asp?id=461",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta popolnoma prosta, brez čakajočih vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:53.746Z"
 },
 {
  "crId": "ba-svilaj",
  "crossing": "Svilaj · kam 2",
  "side": "HAK",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://m.hak.hr/cam.asp?id=462",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Eno vozilo pri rampi, čaka na kontrolo",
  "readable": true,
  "ts": "2026-06-23T21:17:54.267Z"
 },
 {
  "crId": "ba-vardiste",
  "crossing": "GP Višegrad · vstop v BiH",
  "side": "BA",
  "lat": 43.78,
  "lng": 19.4,
  "image": "https://gp.satwork.net/AMSRS_16_GP_VA02/slika.jpg",
  "enter": "BA",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, nobene kolone pri rampi.",
  "readable": true,
  "ts": "2026-06-23T21:17:58.168Z"
 },
 {
  "crId": "ba-vardiste",
  "crossing": "GP Višegrad · izstop iz BiH",
  "side": "BA",
  "lat": 43.78,
  "lng": 19.4,
  "image": "https://gp.satwork.net/AMSRS_16_GP_VA01/slika.jpg",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, nobene kolone vozil.",
  "readable": true,
  "ts": "2026-06-23T21:17:58.839Z"
 },
 {
  "crId": "ba-velika-kladusa",
  "crossing": "Maljevac · kam 1",
  "side": "HAK",
  "lat": 45.18,
  "lng": 15.82,
  "image": "https://m.hak.hr/cam.asp?id=429",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:14.254Z"
 },
 {
  "crId": "ba-velika-kladusa",
  "crossing": "Maljevac · kam 2",
  "side": "HAK",
  "lat": 45.18,
  "lng": 15.82,
  "image": "https://m.hak.hr/cam.asp?id=430",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 1,
  "note": "Malo vozil pri rampi, prostor pred njo",
  "readable": true,
  "ts": "2026-06-23T21:18:14.808Z"
 },
 {
  "crId": "ba-zupci",
  "crossing": "GP Zupci · izstop iz BiH",
  "side": "BA",
  "lat": 42.68,
  "lng": 18.4,
  "image": "https://gp.satwork.net/AMSRS_03_GP_TB02/slika.jpg",
  "enter": "ME",
  "dirLabel": "vstop v Črno goro",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:17:37.438Z"
 },
 {
  "crId": "hr-bajakovo",
  "crossing": "Bajakovo · kam 1",
  "side": "HAK",
  "lat": 45.06,
  "lng": 19.1,
  "image": "https://m.hak.hr/cam.asp?id=2",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Brez kolone, samo eno vozilo pri rampi",
  "readable": true,
  "ts": "2026-06-23T21:18:08.463Z"
 },
 {
  "crId": "hr-bajakovo",
  "crossing": "Bajakovo · kam 2",
  "side": "HAK",
  "lat": 45.06,
  "lng": 19.1,
  "image": "https://m.hak.hr/cam.asp?id=1",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Dve vzporedni koloni pri srbski rampi",
  "readable": true,
  "ts": "2026-06-23T21:18:10.053Z"
 },
 {
  "crId": "hr-batina",
  "crossing": "Batina · kam 1",
  "side": "HAK",
  "lat": 45.85,
  "lng": 18.85,
  "image": "https://m.hak.hr/cam.asp?id=1017",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez vidne kolone vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:12.601Z"
 },
 {
  "crId": "hr-batina",
  "crossing": "Batina · kam 2",
  "side": "HAK",
  "lat": 45.85,
  "lng": 18.85,
  "image": "https://m.hak.hr/cam.asp?id=1018",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri mejni rampi, 2 vozila v vrsti",
  "readable": true,
  "ts": "2026-06-23T21:18:13.031Z"
 },
 {
  "crId": "hr-erdut",
  "crossing": "Erdut · kam 1",
  "side": "HAK",
  "lat": 45.52,
  "lng": 19.05,
  "image": "https://m.hak.hr/cam.asp?id=415",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, ni čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:10.888Z"
 },
 {
  "crId": "hr-erdut",
  "crossing": "Erdut · kam 2",
  "side": "HAK",
  "lat": 45.52,
  "lng": 19.05,
  "image": "https://m.hak.hr/cam.asp?id=416",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, nobene kolone, noč.",
  "readable": true,
  "ts": "2026-06-23T21:18:11.133Z"
 },
 {
  "crId": "hr-ilok",
  "crossing": "Ilok · kam 1",
  "side": "HAK",
  "lat": 45.22,
  "lng": 19.37,
  "image": "https://m.hak.hr/cam.asp?id=417",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri rampi, dve vozili v vrsti",
  "readable": true,
  "ts": "2026-06-23T21:18:11.604Z"
 },
 {
  "crId": "hr-ilok",
  "crossing": "Ilok · kam 2",
  "side": "HAK",
  "lat": 45.22,
  "lng": 19.37,
  "image": "https://m.hak.hr/cam.asp?id=418",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Majhna kolona vozil pri srbski rampi",
  "readable": true,
  "ts": "2026-06-23T21:18:12.213Z"
 },
 {
  "crId": "hr-tovarnik",
  "crossing": "Tovarnik · kam 1",
  "side": "HAK",
  "lat": 45.16,
  "lng": 19.15,
  "image": "https://m.hak.hr/cam.asp?id=419",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona čaka na srbski kontroli",
  "readable": true,
  "ts": "2026-06-23T21:18:09.338Z"
 },
 {
  "crId": "hr-tovarnik",
  "crossing": "Tovarnik · kam 2",
  "side": "HAK",
  "lat": 45.16,
  "lng": 19.15,
  "image": "https://m.hak.hr/cam.asp?id=420",
  "enter": "RS",
  "dirLabel": "vstop v Srbijo",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona vozil pred srbsko kontrolo",
  "readable": true,
  "ts": "2026-06-23T21:18:09.777Z"
 },
 {
  "crId": "si-gruskovje",
  "crossing": "Macelj · kam 2",
  "side": "HAK",
  "lat": 46.29,
  "lng": 15.78,
  "image": "https://m.hak.hr/cam.asp?id=35",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Nočna slika, cesta prosta, brez vidnih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:07.941Z"
 },
 {
  "crId": "si-gruskovje",
  "crossing": "Macelj · kam 1",
  "side": "HAK",
  "lat": 46.29,
  "lng": 15.78,
  "image": "https://m.hak.hr/cam.asp?id=34",
  "enter": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta proti rampi je prazna, brez vozil.",
  "readable": true,
  "ts": "2026-06-23T21:18:08.061Z"
 },
 {
  "crId": "si-obrezje",
  "crossing": "Bregana · kam 1",
  "side": "HAK",
  "lat": 45.84,
  "lng": 15.7,
  "image": "https://m.hak.hr/cam.asp?id=6",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "zmerno",
  "extent": "kratka",
  "lanes": 2,
  "note": "Kratka kolona pri mejni rampi, čakanje HD vozil",
  "readable": true,
  "ts": "2026-06-23T21:18:06.494Z"
 },
 {
  "crId": "si-obrezje",
  "crossing": "Bregana · kam 2",
  "side": "HAK",
  "lat": 45.84,
  "lng": 15.7,
  "image": "https://m.hak.hr/cam.asp?id=7",
  "enter": "HR",
  "dirLabel": "vstop v Hrvaško",
  "level": "prosto",
  "extent": "brez",
  "lanes": 0,
  "note": "Cesta prosta, brez čakajočih vozil v koloni",
  "readable": true,
  "ts": "2026-06-23T21:18:07.323Z"
 }
];
