// SAMODEJNO ZAJETO: AI ocena gnece na mejnih prehodih (Claude Haiku 4.5 vision).
// Steje le vozila v koloni proti rampi (NE parkiranih); locuje smer (vstop v BiH / izstop iz BiH).
// OPOMBA: ocena je PRIBLIZEK iz slike — ni uradni podatek.
export interface AiCongestion { key: string; crossing: string; camName: string; lat: number; lng: number; image: string; dir: string; dirLabel: string; level: string; vehicles: number | null; waitMin: string; note: string; readable: boolean; ts: string }
export const AI_CONGESTION: AiCongestion[] = [
 {
  "key": "43.17,17.49",
  "crossing": "GP Bijača",
  "camName": "GP Bijača",
  "lat": 43.17,
  "lng": 17.49,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/BIJACA.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona proti rampi, promet tekoč",
  "readable": true,
  "ts": "2026-06-08T16:29:57.974Z"
 },
 {
  "key": "45.14,17.99",
  "crossing": "GP Brod",
  "camName": "GP Brod · izstop iz BiH",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://gp.satwork.net/AMSRS_04_GP_BR01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "zmerno",
  "vehicles": 6,
  "waitMin": "5-10",
  "note": "Kolona vozil čaka na mejni rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:43.904Z"
 },
 {
  "key": "45.14,17.99",
  "crossing": "GP Brod",
  "camName": "GP Brod · vstop v BiH",
  "lat": 45.14,
  "lng": 17.99,
  "image": "https://gp.satwork.net/AMSRS_04_GP_BR02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Ni vidne kolone pred rampo",
  "readable": true,
  "ts": "2026-06-08T16:29:41.508Z"
 },
 {
  "key": "43.20,17.65",
  "crossing": "GP Crveni Grm",
  "camName": "GP Crveni Grm",
  "lat": 43.2,
  "lng": 17.65,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/CRVENIGRM.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Brez kolone, normalen promet.",
  "readable": true,
  "ts": "2026-06-08T16:29:56.309Z"
 },
 {
  "key": "43.02,17.55",
  "crossing": "GP Doljani",
  "camName": "GP Doljani - ulaz u BIH",
  "lat": 43.02,
  "lng": 17.55,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/DOLJANI.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Jasne kolone proti rampi ni",
  "readable": true,
  "ts": "2026-06-08T16:29:56.656Z"
 },
 {
  "key": "45.27,16.93",
  "crossing": "GP Gradina (Donja Gradina)",
  "camName": "GP Gradina (Donja Gradina) · izstop iz BiH",
  "lat": 45.27,
  "lng": 16.93,
  "image": "https://gp.satwork.net/AMSRS_08_GP_GD01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "zmerno",
  "vehicles": 6,
  "waitMin": "10-20",
  "note": "Tovornjaki čakajo na carinski pregled",
  "readable": true,
  "ts": "2026-06-08T16:29:39.635Z"
 },
 {
  "key": "45.27,16.93",
  "crossing": "GP Gradina (Donja Gradina)",
  "camName": "GP Gradina (Donja Gradina) · vstop v BiH",
  "lat": 45.27,
  "lng": 16.93,
  "image": "https://gp.satwork.net/AMSRS_08_GP_GD02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona proti rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:37.968Z"
 },
 {
  "key": "45.14,17.25",
  "crossing": "GP Gradiška",
  "camName": "GP Gradiška · izstop iz BiH",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://gp.satwork.net/AMSRS_17_GP_CA01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona pred rampo, promet prost.",
  "readable": true,
  "ts": "2026-06-08T16:29:38.575Z"
 },
 {
  "key": "45.14,17.25",
  "crossing": "GP Gradiška",
  "camName": "GP Gradiška · vstop v BiH",
  "lat": 45.14,
  "lng": 17.25,
  "image": "https://gp.satwork.net/AMSRS_17_GP_CA02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Brez kolone pred mejno rampo.",
  "readable": true,
  "ts": "2026-06-08T16:29:38.153Z"
 },
 {
  "key": "43.34,18.84",
  "crossing": "GP Hum",
  "camName": "GP Hum · izstop iz BiH",
  "lat": 43.34,
  "lng": 18.84,
  "image": "https://gp.satwork.net/AMSRS_13_GP_SP01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Megla, vozilo parkirano ob rampi",
  "readable": false,
  "ts": "2026-06-08T16:29:49.908Z"
 },
 {
  "key": "44.85,15.78",
  "crossing": "GP Izačić",
  "camName": "GP Izačić",
  "lat": 44.85,
  "lng": 15.78,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/IZACIC.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona proti rampi.",
  "readable": true,
  "ts": "2026-06-08T16:29:58.678Z"
 },
 {
  "key": "43.65,16.86",
  "crossing": "GP Kamensko",
  "camName": "GP Kamensko",
  "lat": 43.65,
  "lng": 16.86,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/KAMENSKO.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona proti rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:55.460Z"
 },
 {
  "key": "44.40,19.13",
  "crossing": "GP Karakaj",
  "camName": "GP Karakaj · izstop iz BiH",
  "lat": 44.4,
  "lng": 19.13,
  "image": "https://gp.satwork.net/AMSRS_07_GP_KA01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Prazna carina, brez kolone vozil",
  "readable": true,
  "ts": "2026-06-08T16:29:44.899Z"
 },
 {
  "key": "44.40,19.13",
  "crossing": "GP Karakaj",
  "camName": "GP Karakaj · vstop v BiH",
  "lat": 44.4,
  "lng": 19.13,
  "image": "https://gp.satwork.net/AMSRS_07_GP_KA02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona pred rampo.",
  "readable": true,
  "ts": "2026-06-08T16:29:44.109Z"
 },
 {
  "key": "42.92,18.45",
  "crossing": "GP Klobuk",
  "camName": "GP Klobuk · izstop iz BiH",
  "lat": 42.92,
  "lng": 18.45,
  "image": "https://gp.satwork.net/AMSRS_12_GP_KL01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene kolone pred mejno rampo",
  "readable": true,
  "ts": "2026-06-08T16:29:49.002Z"
 },
 {
  "key": "42.92,18.45",
  "crossing": "GP Klobuk",
  "camName": "GP Klobuk · vstop v BiH",
  "lat": 42.92,
  "lng": 18.45,
  "image": "https://gp.satwork.net/AMSRS_12_GP_KL02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona proti rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:48.337Z"
 },
 {
  "key": "45.22,16.55",
  "crossing": "GP Kostajnica",
  "camName": "GP Kostajnica · izstop iz BiH",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://gp.satwork.net/AMSRS_11_GP_KO01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene vidne kolone proti rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:48.652Z"
 },
 {
  "key": "45.22,16.55",
  "crossing": "GP Kostajnica",
  "camName": "GP Kostajnica · vstop v BiH",
  "lat": 45.22,
  "lng": 16.55,
  "image": "https://gp.satwork.net/AMSRS_11_GP_KO02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 1,
  "waitMin": "0-5",
  "note": "Eno vozilo v mejni rampi, brez kolone",
  "readable": true,
  "ts": "2026-06-08T16:29:47.395Z"
 },
 {
  "key": "45.18,16.81",
  "crossing": "GP Kozarska Dubica",
  "camName": "GP Kozarska Dubica · izstop iz BiH",
  "lat": 45.18,
  "lng": 16.81,
  "image": "https://gp.satwork.net/AMSRS_09_GP_KD01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 1,
  "waitMin": "0-5",
  "note": "Eno vozilo na cesti, brez kolone",
  "readable": true,
  "ts": "2026-06-08T16:29:45.853Z"
 },
 {
  "key": "45.18,16.81",
  "crossing": "GP Kozarska Dubica",
  "camName": "GP Kozarska Dubica · vstop v BiH",
  "lat": 45.18,
  "lng": 16.81,
  "image": "https://gp.satwork.net/AMSRS_09_GP_KD02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Megla, ni vidne kolone vozil",
  "readable": false,
  "ts": "2026-06-08T16:29:45.294Z"
 },
 {
  "key": "45.05,16.38",
  "crossing": "GP Novi Grad",
  "camName": "GP Novi Grad · izstop iz BiH",
  "lat": 45.05,
  "lng": 16.38,
  "image": "https://gp.satwork.net/AMSRS_10_GP_NG01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Jasna cesta, brez kolone proti rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:47.088Z"
 },
 {
  "key": "45.05,16.38",
  "crossing": "GP Novi Grad",
  "camName": "GP Novi Grad · vstop v BiH",
  "lat": 45.05,
  "lng": 16.38,
  "image": "https://gp.satwork.net/AMSRS_10_GP_NG02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Megla, ni vidne jasne kolone",
  "readable": false,
  "ts": "2026-06-08T16:29:46.707Z"
 },
 {
  "key": "45.03,18.69",
  "crossing": "GP Orašje",
  "camName": "GP Orašje - izlaz iz BIH",
  "lat": 45.03,
  "lng": 18.69,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/ORASJE.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "zmerno",
  "vehicles": 8,
  "waitMin": "10-20",
  "note": "Kolona tovornjakov in vozil proti meji",
  "readable": true,
  "ts": "2026-06-08T16:29:55.001Z"
 },
 {
  "key": "44.73,19.31",
  "crossing": "GP Pavlovića most",
  "camName": "GP Pavlovića most · izstop iz BiH",
  "lat": 44.73,
  "lng": 19.31,
  "image": "https://gp.satwork.net/AMSRS_05_GP_PM01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 1,
  "waitMin": "0-5",
  "note": "Samo eno vozilo v koloni prema rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:53.249Z"
 },
 {
  "key": "44.73,19.31",
  "crossing": "GP Pavlovića most",
  "camName": "GP Pavlovića most · vstop v BiH",
  "lat": 44.73,
  "lng": 19.31,
  "image": "https://gp.satwork.net/AMSRS_05_GP_PM02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene kolone proti rampi.",
  "readable": true,
  "ts": "2026-06-08T16:29:52.409Z"
 },
 {
  "key": "43.45,17.28",
  "crossing": "GP Prisika (Aržano)",
  "camName": "GP Prisika (Aržano)",
  "lat": 43.45,
  "lng": 17.28,
  "image": "https://video-nadzor.bihamk.ba/videosurveillence/PRISIKA.jpg",
  "dir": "neznano",
  "dirLabel": "smer neznana",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Slika je črna, kamera ne deluje.",
  "readable": false,
  "ts": "2026-06-08T16:29:57.379Z"
 },
 {
  "key": "44.90,19.32",
  "crossing": "GP Rača",
  "camName": "GP Rača · izstop iz BiH",
  "lat": 44.9,
  "lng": 19.32,
  "image": "https://gp.satwork.net/AMSRS_02_GP_RA01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene kolone pred rampo",
  "readable": true,
  "ts": "2026-06-08T16:29:40.206Z"
 },
 {
  "key": "44.90,19.32",
  "crossing": "GP Rača",
  "camName": "GP Rača · vstop v BiH",
  "lat": 44.9,
  "lng": 19.32,
  "image": "https://gp.satwork.net/AMSRS_02_GP_RA02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Brez vozil v koloni, parkirišče prazno",
  "readable": true,
  "ts": "2026-06-08T16:29:39.422Z"
 },
 {
  "key": "45.10,18.18",
  "crossing": "GP Svilaj",
  "camName": "GP Svilaj · izstop iz BiH",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://gp.satwork.net/AMSRS_14_GP_SV01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "zmerno",
  "vehicles": 8,
  "waitMin": "10-20",
  "note": "Kolona tovornjakov proti mejni rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:50.419Z"
 },
 {
  "key": "45.10,18.18",
  "crossing": "GP Svilaj",
  "camName": "GP Svilaj · vstop v BiH",
  "lat": 45.1,
  "lng": 18.18,
  "image": "https://gp.satwork.net/AMSRS_14_GP_SV02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene kolone pred rampo, promet teče",
  "readable": true,
  "ts": "2026-06-08T16:29:50.055Z"
 },
 {
  "key": "45.06,18.46",
  "crossing": "GP Šamac",
  "camName": "GP Šamac · izstop iz BiH",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://gp.satwork.net/AMSRS_15_GP_SA01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobene kolone pred mejno rampo",
  "readable": true,
  "ts": "2026-06-08T16:29:52.574Z"
 },
 {
  "key": "45.06,18.46",
  "crossing": "GP Šamac",
  "camName": "GP Šamac · vstop v BiH",
  "lat": 45.06,
  "lng": 18.46,
  "image": "https://gp.satwork.net/AMSRS_15_GP_SA02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "zmerno",
  "vehicles": 6,
  "waitMin": "10-20",
  "note": "Kolona tovornjakov proti mejni rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:51.293Z"
 },
 {
  "key": "44.55,19.18",
  "crossing": "GP Šepak",
  "camName": "GP Šepak · izstop iz BiH",
  "lat": 44.55,
  "lng": 19.18,
  "image": "https://gp.satwork.net/AMSRS_06_GP_SP01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Ni kolone pred rampo, promet prost",
  "readable": true,
  "ts": "2026-06-08T16:29:43.555Z"
 },
 {
  "key": "44.55,19.18",
  "crossing": "GP Šepak",
  "camName": "GP Šepak · vstop v BiH",
  "lat": 44.55,
  "lng": 19.18,
  "image": "https://gp.satwork.net/AMSRS_06_GP_SP02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Vidna megla, rampa jasno vidna",
  "readable": false,
  "ts": "2026-06-08T16:29:42.308Z"
 },
 {
  "key": "43.78,19.40",
  "crossing": "GP Višegrad",
  "camName": "GP Višegrad · izstop iz BiH",
  "lat": 43.78,
  "lng": 19.4,
  "image": "https://gp.satwork.net/AMSRS_16_GP_VA01/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Nobena kolona pred rampo",
  "readable": true,
  "ts": "2026-06-08T16:29:54.134Z"
 },
 {
  "key": "43.78,19.40",
  "crossing": "GP Višegrad",
  "camName": "GP Višegrad · vstop v BiH",
  "lat": 43.78,
  "lng": 19.4,
  "image": "https://gp.satwork.net/AMSRS_16_GP_VA02/slika.jpg",
  "dir": "vstop",
  "dirLabel": "vstop v BiH",
  "level": "prosto",
  "vehicles": 0,
  "waitMin": "0-5",
  "note": "Ni vozil v koloni tegen rampi.",
  "readable": true,
  "ts": "2026-06-08T16:29:55.030Z"
 },
 {
  "key": "42.68,18.40",
  "crossing": "GP Zupci",
  "camName": "GP Zupci · izstop iz BiH",
  "lat": 42.68,
  "lng": 18.4,
  "image": "https://gp.satwork.net/AMSRS_03_GP_TB02/slika.jpg",
  "dir": "izstop",
  "dirLabel": "izstop iz BiH",
  "level": "zmerno",
  "vehicles": 6,
  "waitMin": "5-10",
  "note": "Vozila čakajo v koloni proti mejni rampi",
  "readable": true,
  "ts": "2026-06-08T16:29:40.864Z"
 }
];
